# Generated by Django 2.2.12 on 2020-05-12 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razaoSocial', models.CharField(max_length=150, verbose_name='Razão Social')),
                ('nomeFantasia', models.CharField(max_length=100, verbose_name='Nome Fantasia')),
                ('cep', models.CharField(max_length=8, verbose_name='CEP')),
                ('endereco', models.CharField(max_length=200, verbose_name='Endereço')),
                ('numero', models.CharField(max_length=10, verbose_name='Numero')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
                ('cnpj', models.CharField(max_length=11, verbose_name='CNPJ')),
                ('consumidorFinal', models.BooleanField(default=False, verbose_name='Consumidor Final')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
        ),
    ]
